menu:
    home: /
    blog: /archives/
    rss: /atom.xml
    github: https://github.com/caiwangwhu

favicon: /favicon.png

#google_analytics: UA-65933410-1
#baidu_analytics: //hm.baidu.com/hm.js?a36e15d9e2adec9a21fcdd9f686b1ed2

selfIntro:
    title: jonytsai
    content: 么么哒
    social:
        github: https://github.com/caiwangwhu
        weibo: http://weibo.com/caiwangwhu